### ISSUE TITLE
Collections routes need redirect

### ISSUE THREAD

**Issue by hadro** [internetarchive/iiif#15]
As identified on the [IIIF Slack](https://iiif.slack.com/archives/C0AL6BU76/p1694642459434369?thread_ts=1694633247.632699&cid=C0AL6BU76) following the IIIF/IA community call, we're missing a redirect route for collections manifest generation to match the routing we do for regular manifest generation.

I believe the following additions to app.py should cover it, but I welcome review by others:

```python
@app.route('/iiif/<identifier>/collection.json')
@cache.cached(timeout=cache_timeouts["long"], forced_update=cache_bust)
def collection(identifier):
    return redirect(f'/iiif/3/{identifier}/collection.json', code=302)

@app.route('/iiif/<identifier>/<page>/collection.json')
@cache.cached(timeout=cache_timeouts["long"], forced_update=cache_bust)
def collectionPage(identifier, page):
    return redirect(f'/iiif/3/{identifier}/{page}/collection.json', code=302)
```

**Comment by glenrobson** [comment]
Enhancement:

Add check if metadata type="collection" then redirect to collection.json as a helper in case someone has asked for a manifest.json for a colleciton .

**Comment by digitaldogsbody** [comment]
I've added the redirects - but I will discuss it at the call this evening, as we don't actually do a redirect for the manifests, just serve the version with /3/ from the unversioned endpoint

**Comment by digitaldogsbody** [comment]
Also added the redirect from manifest.json -> collection.json when appropriate
