### ISSUE TITLE
Internal Server Error when fetching manifests

### ISSUE THREAD

**Issue by sammeltassen** [internetarchive/iiif#17]
Maybe too early too soon (too enthusiastic about this!) but I tested out the new manifests for the IA items on the [Gilly's Library](https://www.gillys-library.org) website that I maintain. Only a single one gave a successful response (see the list below); the rest returned an Internal Server Error. Books come from the collections of the [Getty Research Institute](https://archive.org/details/getty), and one from the [Smithsonian Libraries and Archives](https://archive.org/details/@smithsonianlibraries).

https://iiif.archive.org/iiif/gri_33125008667756/manifest.json
https://iiif.archive.org/iiif/gri_33125012605529/manifest.json
https://iiif.archive.org/iiif/gri_33125008297349/manifest.json
https://iiif.archive.org/iiif/gri_33125008667582/manifest.json
https://iiif.archive.org/iiif/gri_33125009324597/manifest.json
https://iiif.archive.org/iiif/gri_33125008626158/manifest.json
https://iiif.archive.org/iiif/gri_33125009548336/manifest.json 🎉
https://iiif.archive.org/iiif/gri_33125010859516/manifest.json
https://iiif.archive.org/iiif/gri_33125011111214/manifest.json
https://iiif.archive.org/iiif/gri_33125010907554/manifest.json
https://iiif.archive.org/iiif/gri_33125011183007/manifest.json
https://iiif.archive.org/iiif/ioannisbaptista00pira/manifest.json (Smithsonian)
https://iiif.archive.org/iiif/gri_33125008262210/manifest.json
https://iiif.archive.org/iiif/gri_33125008527570/manifest.json
https://iiif.archive.org/iiif/gri_33125011113459/manifest.json
https://iiif.archive.org/iiif/gri_33125009747607/manifest.json
https://iiif.archive.org/iiif/gri_33125008448025/manifest.json
https://iiif.archive.org/iiif/gri_33125012907867/manifest.json
https://iiif.archive.org/iiif/altedenkmalerde00winc/manifest.json
https://iiif.archive.org/iiif/gri_33125010864763/manifest.json
https://iiif.archive.org/iiif/gri_33125012602732/manifest.json
https://iiif.archive.org/iiif/gri_33125010908289/manifest.json
https://iiif.archive.org/iiif/gri_33125010884381/manifest.json
https://iiif.archive.org/iiif/veuesdeversaille00swid/manifest.json
https://iiif.archive.org/iiif/02413153.5462.emory.edu/manifest.json
https://iiif.archive.org/iiif/gri_33125011118912/manifest.json
https://iiif.archive.org/iiif/segmentanobilium00perr/manifest.json
https://iiif.archive.org/iiif/gri_33125008676393/manifest.json

**Comment by hadro** [comment]
Hi Jules, thanks for testing, and for your enthusiasm :)
I did not test every single one of these, but at a glance I believe that the fix proposed in #14 should handle most if not all of these -- and should be a fix incorporated pretty soon!
Stay tuned, and many thanks.

**Comment by sammeltassen** [comment]
Good to know! Thanks!

**Comment by glenrobson** [comment]
Discussed in catchup on 14th of Sept. Wait till #14 is completed then check these before closing.

**Comment by sammeltassen** [comment]
@hadro The manifests above still return internal server errors; are you sure this is fixed?
