### ISSUE TITLE
V2 legacy route for manifests is still using ArchiveLab infrastructure?

### ISSUE THREAD

**Issue by hadro** [internetarchive/iiif#26]
See in this manifest, for example: 
https://iiif.archive.org/iiif/2/1991-12-compute-magazine/manifest.json

All the images are being requested via the code on archivelabs, e.g.: 
https://iiif.archivelab.org/iiif/1991-12-compute-magazine$44/full/full/0/default.jpg

And all the `@ids` are referencing Archivelab as well. 

Is that as intended?

**Comment by glenrobson** [comment]
Two options:

1. alias iiif.archivelab.org to  iiif.archive.org and shutoff the labs service
2. Change the manfiest 2 generation so that it creates iiif.archive.org IDs.

Currently the issue is that v2 is using the old image server not Cantaloupe.

**Comment by digitaldogsbody** [comment]
I think at the least we should change the v2 generation to use Cantaloupe for serving the images, even if we keep the archivelabs ids for everything else. This could also help with the second issue in #16

**Comment by glenrobson** [comment]
Agreed to go with option 2.

**Comment by glenrobson** [comment]
Complete.
