### ISSUE TITLE
Should cantaloupe resolver default to /2/ or /3/?

### ISSUE THREAD

**Issue by hadro** [internetarchive/iiif#28]
In writing the documentation, it seems the `/identifier/info.json` route will be really useful for helping folks figure out how to get an image API url without having to dig through the manifest generation first.

However, in testing this out, I noticed that version 2 of the Image API is hardcoded into app.py -- is this on purpose? 

Code is here: 
https://github.com/internetarchive/iiif/blob/96ce8358532e97f984da59bcef585f8f12e4f3aa/iiify/app.py#L169
and similarly here: 
https://github.com/internetarchive/iiif/blob/96ce8358532e97f984da59bcef585f8f12e4f3aa/iiify/app.py#L176

I think there's a strong argument to be made that the default should be /3/, not /2/, but happy to discuss.

**Comment by glenrobson** [comment]
As discussed last night the `/indentifier/info.json` route is used in the v2 manifest so while we could update it to 3 for now when we transfer the iiif.archivelabs domain name to iiif.archive.org the v2 manifests would have v3 images.
