### ISSUE TITLE
Some v3 manifests not yet generated

### ISSUE THREAD

**Issue by mprove** [internetarchive/iiif#43]
For the book https://archive.org/details/mediaevalleicest00billrich 
the manifest v2 is ok: https://iiif.archive.org/iiif/2/mediaevalleicest00billrich/manifest.json
while the manifest v3 is missing: https://iiif.archive.org/iiif/mediaevalleicest00billrich/manifest.json
Should it be https://iiif.archive.org/iiif/3/mediaevalleicest00billrich/manifest.json ? That does not exist either. 

Is this work in progress? Or did I get the v3 URL wrong?

**Comment by digitaldogsbody** [comment]
This is due to missing metadata in the underlying IA API which we previously weren't handling well. The fix for this has been made and merged already in #22, and is just pending deployment into production.

**Comment by regisrob** [comment]
Same problem with this item: https://archive.org/details/lelivredestroisv00chri
- archivelab OK: https://iiif.archivelab.org/iiif/lelivredestroisv00chri/manifest.json
- archive v2 OK: https://iiif.archive.org/iiif/2/lelivredestroisv00chri/manifest.json 
- archive v3 `500 Internal Server Error`: https://iiif.archive.org/iiif/lelivredestroisv00chri/manifest.json

**Comment by digitaldogsbody** [comment]
I've checked against my local instance and this manifest should also be fixed when the latest code is deployed to production

**Comment by digitaldogsbody** [comment]
The latest code is now deployed, so these manifests are now working :)

**Comment by mprove** [comment]
confirmed. terrific job!
