### ISSUE TITLE
No items for Steamboat Willie manifest?

### ISSUE THREAD

**Issue by hadro** [internetarchive/iiif#58]
Not sure why, but this manifest is not showing any items even though there seem to be two viable files on the IA item page:
- https://iiif.archive.org/iiif/3/steamboat-willie-16mm-film-scan-4k-lossless/manifest.json
- https://archive.org/details/steamboat-willie-16mm-film-scan-4k-lossless

(All of that's a separate issue from the fact that the MOV file is a whopping 34gb!)

**Comment by glenrobson** [comment]
Currently showing a 500 error.

**Comment by glenrobson** [comment]
Errors running locally:

```
pydantic.error_wrappers.ValidationError: 60 validation errors for Manifest
thumbnail -> 0 -> __root__ -> id -> __root__
  URL invalid, extra characters found after valid URL: ' Willie [16mm Film Scan]_ProRes (3400x2550)_000001.jpg' (type=value_error.url.extra; extra= Willie [16mm Film Scan]_ProRes (3400x2550)_000001.jpg)
```

Probably need to URL encode the thumbnail URL.

**Comment by glenrobson** [comment]
These thumbnails are causing the issue:

https://archive.org/download/steamboat-willie-16mm-film-scan-4k-lossless/steamboat-willie-16mm-film-scan-4k-lossless.thumbs/
