### ISSUE TITLE
504 Gateway Time-out on IIIF image and presentation manifest requests

### ISSUE THREAD

**Issue by mprove** [internetarchive/iiif#60]
Since yesterday 22-Feb-2024 I get "504 Gateway Time-out" on all IIIF image calls and even on some IIIF presentation calls. 
2 examples:
resource (ok): https://archive.org/details/TNM_Handwritten_notes_Ted_Nelson_20180227_0129
manifest (ok): https://iiif.archive.org/iiif/TNM_Handwritten_notes_Ted_Nelson_20180227_0129/manifest.json
image (504): https://iiif.archive.org/image/iiif/3/TNM_Handwritten_notes_Ted_Nelson_20180227_0129%2FTNM_Handwritten_notes_Ted_Nelson_20180227_0129_jp2.zip%2FTNM_Handwritten_notes_Ted_Nelson_20180227_0129_jp2%2FTNM_Handwritten_notes_Ted_Nelson_20180227_0129_0000.jp2/full/max/0/default.jpg 

resource (ok): https://archive.org/details/VE-IMG-17305
manifest (504): https://iiif.archive.org/iiif/3/VE-IMG-17305/manifest.json 
image (504): https://iiif.archive.org/image/iiif/3/VE-IMG-17305%2Fnazca_IKO_2001015.jpg/full/max/0/default.jpg

**Comment by mprove** [comment]
fixed. No problems anymore.

**Comment by mprove** [comment]
again: 504

**Comment by digitaldogsbody** [comment]
IA staff have bumped the allocated resources for the service, so hopefully these problems should now be resolved

**Comment by mprove** [comment]
ok, let me do some rough checks. Most of the stuff looks much better already. Some issues:

error 500 Internal Server Error. Java heap space. java.lang.OutOfMemoryError: Java heap space )  for

- https://iiif.archive.org/image/iiif/3/mapofgreatbritai00jcsm%2Fmapofgreatbritai00jcsm_jp2.zip%2Fmapofgreatbritai00jcsm_jp2%2Fmapofgreatbritai00jcsm_0000.jp2/pct:3,5,95,96/max/0/default.jpg  
- https://iiif.archive.org/image/iiif/3/map198204072%2F1982-04-072.TIF/pct:2,3,93,94/max/0/default.jpg 
- https://iiif.archive.org/image/iiif/3/herzogthum-braunschweig-karte%2FHerzogthum%20Braunschweig%20-%20Karte.jpg/pct:9,10,76,79/max/0/default.jpg 
- https://iiif.archive.org/image/iiif/3/dr_view-plate-39-church-of-st-mary-of-the-manger-at-bethlehem-church-of-12190324%2F12190324.jp2/pct:10,8,87,84/max/0/default.jpg
- https://iiif.archive.org/image/iiif/3/dr_view-plate-39-church-of-st-mary-of-the-manger-at-bethlehem-church-of-12190324%2F12190324.jp2/pct:10,8,87,84/max/0/default.jpg 

At least Error 500 is four places better than 504!  ;o)   (And the majority of my tests are ok.)

**Comment by mprove** [comment]
ok, I consider 504 issues as resolved.
I've opened a new issuer for error 500 >> #65
