### ISSUE TITLE
Multi-segment video produces no items

### ISSUE THREAD

**Issue by benwbrum** [internetarchive/iiif#70]
Several items in the TV News Archive collection are displayed in the IA viewer in segments with summaries under them.  This appears to be the result of a different ingestion/derivation process, possibly related to web scraping.

The manifests we produce from these items contain no `items` at all, so we have effectively no support for them.

Further research should be done on the ways these items work and how to map them to the IIIF presentation API.

Examples:
* [CSPAN3 Poplar Forest Archaeology](https://iiif.archive.org/iiif/helper/CSPAN3_20180217_164800_Poplar_Forest_Archaeology/)
* [TV News Archive](https://archive.org/details/tvnews)

Note that these items also appear to have captions located in `txt` files, which the IA viewer is displaying correctly.

**Comment by saracarl** [comment]
The first example here gives a 403 error when you try to load the media file, quite likely because it is under copyright.  We perhaps should just fail gracefully if we don't think we can play it.

**Comment by glenrobson** [comment]
We found this URL for accessing regions of stream only recordings:

https://ia801803.us.archive.org/29/items/CSPAN3_20180217_164800_Poplar_Forest_Archaeology/CSPAN3_20180217_164800_Poplar_Forest_Archaeology.mp4?start=0&end=360&ignore=x.mp4&cnt=0

start and end are in mintues and the IA seem to ask for 1 minute segments.

Discussed this as one canvas with segments in image.

**Comment by benwbrum** [comment]
The relevant parts of the metadata API response are:
```json
"dir": "/29/items/CSPAN3_20180217_164800_Poplar_Forest_Archaeology",
"metadata": {
    "runtime": "00:13:00",
    "access-restricted-item": "true"
  },
  "server": "ia601803.us.archive.org",
  ```

**Comment by benwbrum** [comment]
We suspect that `access-restricted-item` is what triggers this logic, but are not sure.  `dir` is needed for the `/29/items` prefix, and `server` for the hostname.

**Comment by glenrobson** [comment]
Accessing text as srt:

https://archive.org/download/CSPAN3_20180217_164800_Poplar_Forest_Archaeology/CSPAN3_20180217_164800_Poplar_Forest_Archaeology.cc5.srt?t=0/360

**Comment by benwbrum** [comment]
Closed captions are available in `.srt` format, with the same time length restrictions that apply to the video content.

It would be straightforward to convert SRT to WebVTT, or at least [ChatGPT thinks so](https://chatgpt.com/share/e1f213e5-0b5a-4e3e-b647-b897ce53aaba) so it would be nice to include them as captions.  Modeling the segments as a single WebVTT annotation targeting the entire canvas or as separate annotations corresponding to the video segments is a harder problem.
