### ISSUE TITLE
Replicate the https://iiif.archivelab.org/iiif/jewishinterpreta00morg$267/info.json structure for v3

### ISSUE THREAD

**Issue by glenrobson** [internetarchive/iiif#79]
See https://github.com/ArchiveLabs/iiif.archivelab.org/issues/144 for background but currently its difficult to guess the image identifier without knowing the original filename as the following URL:

https://iiif.archive.org/iiif/jewishinterpreta00morg$267/info.json

Redirects to:

https://iiif.archive.org/image/iiif/2/jewishinterpreta00morg%2fjewishinterpreta00morg_jp2.zip%2fjewishinterpreta00morg_jp2%2fjewishinterpreta00morg_0267.jp2/info.json

It would be useful if you could do something like:

https://iiif.archive.org/iiif/3/jewishinterpreta00morg$267/info.json

To get to the version 3 of the image. This would also be useful for the IIIF training.

**Comment by afarlie** [comment]
(aside: Something that I would also appreciate is ifff.archive.org/ifff/3/<id>$<page>/ocr.josn to get the page text, as my use case for wikisource.  Currently wikisource uses varios OCR's, but being able to pull the OCR directly for a page would be useful. )
